//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FB2Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FB2Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите прервать выполнение текущей операции?.
        /// </summary>
        internal static string ConfirmationCancel {
            get {
                return ResourceManager.GetString("ConfirmationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        internal static string ConfirmationCaption {
            get {
                return ResourceManager.GetString("ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите очистить список файлов?.
        /// </summary>
        internal static string ConfirmationClearFileList {
            get {
                return ResourceManager.GetString("ConfirmationClearFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите архивировать {0} файл(ов)?.
        /// </summary>
        internal static string ConfirmationCompress {
            get {
                return ResourceManager.GetString("ConfirmationCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить {0} файл(ов)?.
        /// </summary>
        internal static string ConfirmationDelete {
            get {
                return ResourceManager.GetString("ConfirmationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить файл &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmationDeleteFile {
            get {
                return ResourceManager.GetString("ConfirmationDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите распаковать {0} файл(ов)?.
        /// </summary>
        internal static string ConfirmationExtract {
            get {
                return ResourceManager.GetString("ConfirmationExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите перекодировать {0} файл(ов) в кодировку {1}?.
        /// </summary>
        internal static string ConfirmationRecode {
            get {
                return ResourceManager.GetString("ConfirmationRecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите скрыть {0} файл(ов)?.
        /// </summary>
        internal static string ConfirmationRemove {
            get {
                return ResourceManager.GetString("ConfirmationRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите скрыть файл &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmationRemoveFile {
            get {
                return ResourceManager.GetString("ConfirmationRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите переименовать имена {0} файлов используя профиль &apos;{1}&apos;?.
        /// </summary>
        internal static string ConfirmationRename {
            get {
                return ResourceManager.GetString("ConfirmationRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите проверить {0} файл(ов) на соответствие спецификации FictionBook v2.1?.
        /// </summary>
        internal static string ConfirmationValidation {
            get {
                return ResourceManager.GetString("ConfirmationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка копирования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string CopyFileError {
            get {
                return ResourceManager.GetString("CopyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование &apos;{0}&apos; отменено, &apos;{1}&apos;  уже существует.
        /// </summary>
        internal static string CopyFileSkipped {
            get {
                return ResourceManager.GetString("CopyFileSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; скопирован в &apos;{1}&apos;.
        /// </summary>
        internal static string CopyFileSuccess {
            get {
                return ResourceManager.GetString("CopyFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Без серии).
        /// </summary>
        internal static string DisplayNoSerie {
            get {
                return ResourceManager.GetString("DisplayNoSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняю комманду &apos;{0}&apos; параметры &apos;{1}&apos;....
        /// </summary>
        internal static string ExecuteCommand {
            get {
                return ResourceManager.GetString("ExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выполнения команды &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ExecuteCommandError {
            get {
                return ResourceManager.GetString("ExecuteCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выполнения команды &apos;{0}&apos; - пустая строка.
        /// </summary>
        internal static string ExecuteCommandErrorEmpty {
            get {
                return ResourceManager.GetString("ExecuteCommandErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширение файла &apos;{0}&apos; не совпадает с &apos;{1}&apos;....
        /// </summary>
        internal static string ExecuteCommandWrongExtension {
            get {
                return ResourceManager.GetString("ExecuteCommandWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание файла &apos;{0}&apos;:.
        /// </summary>
        internal static string FileDescriptionView {
            get {
                return ResourceManager.GetString("FileDescriptionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Кб.
        /// </summary>
        internal static string FileSizeText {
            get {
                return ResourceManager.GetString("FileSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка перемещения &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string MoveFileError {
            get {
                return ResourceManager.GetString("MoveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещение &apos;{0}&apos; отменено, &apos;{1}&apos;  уже существует.
        /// </summary>
        internal static string MoveFileSkip {
            get {
                return ResourceManager.GetString("MoveFileSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; перемещен в &apos;{1}&apos;.
        /// </summary>
        internal static string MoveFileSuccess {
            get {
                return ResourceManager.GetString("MoveFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл уже существует &apos;{0}&apos;.
        /// </summary>
        internal static string OverwriteDialofFileAlreadyExists {
            get {
                return ResourceManager.GetString("OverwriteDialofFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет фамилии автора..
        /// </summary>
        internal static string ParseFileErrorNoAuthorLastName {
            get {
                return ResourceManager.GetString("ParseFileErrorNoAuthorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет жанра книги..
        /// </summary>
        internal static string ParseFileErrorNoBookGenre {
            get {
                return ResourceManager.GetString("ParseFileErrorNoBookGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет уникального идентификатора.
        /// </summary>
        internal static string ParseFileErrorNoBookID {
            get {
                return ResourceManager.GetString("ParseFileErrorNoBookID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет названия книги..
        /// </summary>
        internal static string ParseFileErrorNoBookTitle {
            get {
                return ResourceManager.GetString("ParseFileErrorNoBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаю список из {0} файлов....
        /// </summary>
        internal static string ParseFileListLoad {
            get {
                return ResourceManager.GetString("ParseFileListLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция прервана пользователем..
        /// </summary>
        internal static string ProgressCancelledByUser {
            get {
                return ResourceManager.GetString("ProgressCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивирую файл &apos;{0}&apos;....
        /// </summary>
        internal static string ProgressCompressFile {
            get {
                return ResourceManager.GetString("ProgressCompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; уже в архиве.
        /// </summary>
        internal static string ProgressCompressFileAlreadyCompressed {
            get {
                return ResourceManager.GetString("ProgressCompressFileAlreadyCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка архивирования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressCompressFileError {
            get {
                return ResourceManager.GetString("ProgressCompressFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирую метаданные файла &apos;{0}&apos;....
        /// </summary>
        internal static string ProgressEditFile {
            get {
                return ResourceManager.GetString("ProgressEditFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка редактирования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressEditFileError {
            get {
                return ResourceManager.GetString("ProgressEditFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перекодирую &apos;{0}&apos; в &apos;{1}&apos;....
        /// </summary>
        internal static string ProgressEncoding {
            get {
                return ResourceManager.GetString("ProgressEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; уже в кодировке &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressEncodingAlreadyEncoded {
            get {
                return ResourceManager.GetString("ProgressEncodingAlreadyEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка перекодирования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressEncodingError {
            get {
                return ResourceManager.GetString("ProgressEncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковываю файл &apos;{0}&apos;....
        /// </summary>
        internal static string ProgressExtractFile {
            get {
                return ResourceManager.GetString("ProgressExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; уже распакован.
        /// </summary>
        internal static string ProgressExtractFileAlreadyExtracted {
            get {
                return ResourceManager.GetString("ProgressExtractFileAlreadyExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка распаковки &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressExtractFileError {
            get {
                return ResourceManager.GetString("ProgressExtractFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; уже загружен.
        /// </summary>
        internal static string ProgressFileAlreadyLoaded {
            get {
                return ResourceManager.GetString("ProgressFileAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружен файл &apos;{0}&apos;.
        /// </summary>
        internal static string ProgressFileLoaded {
            get {
                return ResourceManager.GetString("ProgressFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressFileLoadError {
            get {
                return ResourceManager.GetString("ProgressFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; перемещен в &apos;{1}&apos;.
        /// </summary>
        internal static string ProgressFileMoved {
            get {
                return ResourceManager.GetString("ProgressFileMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; (новое имя: &apos;{1}&apos;).
        /// </summary>
        internal static string ProgressFileMoveError {
            get {
                return ResourceManager.GetString("ProgressFileMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} -&gt; {1}.
        /// </summary>
        internal static string ProgressFileSizeChange {
            get {
                return ResourceManager.GetString("ProgressFileSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирую &apos;{0}&apos;....
        /// </summary>
        internal static string ProgressScanFolder {
            get {
                return ResourceManager.GetString("ProgressScanFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирую файл &apos;{0}&apos; на соответствие спецификации....
        /// </summary>
        internal static string ProgressValidation {
            get {
                return ResourceManager.GetString("ProgressValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка переименования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string RenameFileError {
            get {
                return ResourceManager.GetString("RenameFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименование &apos;{0}&apos; отменено, &apos;{1}&apos;  уже существует.
        /// </summary>
        internal static string RenameFileSkip {
            get {
                return ResourceManager.GetString("RenameFileSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; переименован в &apos;{1}&apos;.
        /// </summary>
        internal static string RenameFileSuccess {
            get {
                return ResourceManager.GetString("RenameFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string RenameMenuName {
            get {
                return ResourceManager.GetString("RenameMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовываю &apos;{0}&apos;....
        /// </summary>
        internal static string RenameZIPtoFB2ZIP {
            get {
                return ResourceManager.GetString("RenameZIPtoFB2ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмечено {0} из {1} файл(ов).
        /// </summary>
        internal static string StatusBarFilesCount {
            get {
                return ResourceManager.GetString("StatusBarFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Транслит).
        /// </summary>
        internal static string TranslitMenuText {
            get {
                return ResourceManager.GetString("TranslitMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка (строка {0}, позиция {1}): {2}.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор присутствует более одного раза: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorDuplicateId {
            get {
                return ResourceManager.GetString("ValidationErrorDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая ссыка &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorEmptyLink {
            get {
                return ResourceManager.GetString("ValidationErrorEmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой элемент: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorEmptyTag {
            get {
                return ResourceManager.GetString("ValidationErrorEmptyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешняя ссылка: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorExternalLink {
            get {
                return ResourceManager.GetString("ValidationErrorExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешняя запись: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorExternalNote {
            get {
                return ResourceManager.GetString("ValidationErrorExternalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная внешняя ссылка: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorInvalidExternalLink {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальная внешняя ссылка: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorLocalExternalLink {
            get {
                return ResourceManager.GetString("ValidationErrorLocalExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет ссылок на объект: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorNoLinksToObject {
            get {
                return ResourceManager.GetString("ValidationErrorNoLinksToObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на несуществующий объект: &apos;{0}&apos;.
        /// </summary>
        internal static string ValidationErrorReferenceToAnUnknown {
            get {
                return ResourceManager.GetString("ValidationErrorReferenceToAnUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка тестирования &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string ValidationFileError {
            get {
                return ResourceManager.GetString("ValidationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OK.
        /// </summary>
        internal static string ValidationOk {
            get {
                return ResourceManager.GetString("ValidationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недочет (строка {0}, позиция {1}): {2}.
        /// </summary>
        internal static string ValidationWarning {
            get {
                return ResourceManager.GetString("ValidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив содержит более чем 1 файл.
        /// </summary>
        internal static string ZipErrorMoreThanOneFile {
            get {
                return ResourceManager.GetString("ZipErrorMoreThanOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив не содержит файлов FB2.
        /// </summary>
        internal static string ZipErrorNoFB2 {
            get {
                return ResourceManager.GetString("ZipErrorNoFB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив не содержит файлов.
        /// </summary>
        internal static string ZipErrorNoFiles {
            get {
                return ResourceManager.GetString("ZipErrorNoFiles", resourceCulture);
            }
        }
    }
}
